program: src.train
method: grid
parameters:
  model:
    values:
      - "bert-base-cased"
      - "roberta-base"
      - "microsoft/deberta-base"
      - "distilbert-base-uncased"
      - "google/canine-c"
      - "xlnet-base-cased"
  profile:
    values:
      - "src/profiles/baseline.yaml"
      - "src/profiles/orthographic/orthographic_p0.1_train_all.yaml"
      - "src/profiles/orthographic/orthographic_p0.2_train_all.yaml"
      - "src/profiles/orthographic/orthographic_p0.3_train_all.yaml"
      - "src/profiles/semantic/semantic_p0.1_train_all.yaml"
      - "src/profiles/semantic/semantic_p0.2_train_all.yaml"
      - "src/profiles/semantic/semantic_p0.3_train_all.yaml"
      #- "src/profiles/orthographic/orthographic_p0.1_train_protect.yaml"
      #- "src/profiles/orthographic/orthographic_p0.2_train_protect.yaml"
      #- "src/profiles/orthographic/orthographic_p0.3_train_protect.yaml"
      #- "src/profiles/semantic/semantic_p0.1_train_protect.yaml"
      #- "src/profiles/semantic/semantic_p0.2_train_protect.yaml"
      #- "src/profiles/semantic/semantic_p0.3_train_protect.yaml"
      - "src/profiles/label-noise/label-noise_p0.1_train.yaml"
      - "src/profiles/label-noise/label-noise_p0.2_train.yaml"
      - "src/profiles/label-noise/label-noise_p0.3_train.yaml"
      - "src/profiles/syntactic/syntactic_p0.1_train.yaml"
      - "src/profiles/syntactic/syntactic_p0.2_train.yaml"
      - "src/profiles/syntactic/syntactic_p0.3_train.yaml"
  lr:
    values: [3e-5] # 3e-5, 3e-4
  seed:
    values: [42] # 331, 42, 20301

command:
  - ${env}
  - python
  - -m
  - ${program}
  - ${args}